# Generated by Django 5.2 on 2025-12-30 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='qr_code_token',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
