# Generated by Django 5.2.8 on 2025-12-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menuitem_restaurant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='meal_type',
            field=models.CharField(choices=[('starters', 'Starters'), ('main_course', '<Main Course'), ('desserts', 'Desserts'), ('drinks', 'Drinks'), ('specials', 'Specials')], max_length=20),
        ),
    ]
